[package]
name = "parse_dwarf"
version = "0.1.0"
authors = ["KyleMiles <kyle@vector35.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gimli = "0.23.0"
binaryninja = { path = "../../" }
